[project]
name = "dcba"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Michał Czuba", email = "michal.czuba.1995@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
]

[project.scripts]
dcba = "dcba:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"
